/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package derivadas;

/**
 *
 * @author alumno
 */
import java.io.*;
import java.util.*;
import java.math.*;

public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

   // boolean constante=false;
      String Kstring, Xstring, Nstring, funcion, ResultadoString;
      int Kint, Xint, Nint, resta, ExponenteInt, ResultadoInt=0;
      double ExponenteDouble, angulo, angulo2, ResultadoDouble=0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FUNCION = new javax.swing.JTextField();
        CONSTANTE = new javax.swing.JButton();
        LINEAL = new javax.swing.JButton();
        POTENCIAL = new javax.swing.JButton();
        SUMA = new javax.swing.JButton();
        PRODUCTO = new javax.swing.JButton();
        COCIENTE = new javax.swing.JButton();
        TRIGONOMETRICA = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DERIVADA = new javax.swing.JTextField();
        X = new javax.swing.JTextField();
        W = new javax.swing.JTextField();
        Wfuncion = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        N = new javax.swing.JTextField();
        Coseno = new javax.swing.JButton();
        Seno = new javax.swing.JButton();
        Tangente = new javax.swing.JButton();
        Secante = new javax.swing.JButton();
        Cosecante = new javax.swing.JButton();
        Cotangente = new javax.swing.JButton();
        BORRAR = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Ufuncion = new javax.swing.JLabel();
        Vfuncion = new javax.swing.JLabel();
        K1 = new javax.swing.JTextField();
        U = new javax.swing.JTextField();
        V = new javax.swing.JTextField();
        RESULTADO = new javax.swing.JButton();
        UVWTrigonometrica = new javax.swing.JRadioButton();
        UVWConstante = new javax.swing.JRadioButton();
        UVWLineal = new javax.swing.JRadioButton();
        UVWPotencial = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        UVWCotangente = new javax.swing.JRadioButton();
        UVWCoseno = new javax.swing.JRadioButton();
        UVWSeno = new javax.swing.JRadioButton();
        UVWTangente = new javax.swing.JRadioButton();
        UVWSecante = new javax.swing.JRadioButton();
        UVWCosecante = new javax.swing.JRadioButton();
        CasillaW = new javax.swing.JCheckBox();
        CasillaU = new javax.swing.JCheckBox();
        CasillaV = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FUNCION.setBackground(new java.awt.Color(204, 204, 204));
        FUNCION.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        FUNCION.setEnabled(false);
        FUNCION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FUNCIONActionPerformed(evt);
            }
        });
        getContentPane().add(FUNCION, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 320, 35));

        CONSTANTE.setBackground(new java.awt.Color(102, 255, 204));
        CONSTANTE.setText("CONSTANTE");
        CONSTANTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONSTANTEActionPerformed(evt);
            }
        });
        getContentPane().add(CONSTANTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 127, -1));

        LINEAL.setBackground(new java.awt.Color(102, 255, 204));
        LINEAL.setText("LINEAL");
        LINEAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LINEALActionPerformed(evt);
            }
        });
        getContentPane().add(LINEAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        POTENCIAL.setBackground(new java.awt.Color(102, 255, 204));
        POTENCIAL.setText("POTENCIAL");
        POTENCIAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                POTENCIALActionPerformed(evt);
            }
        });
        getContentPane().add(POTENCIAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        SUMA.setBackground(new java.awt.Color(102, 255, 204));
        SUMA.setText("SUMA ALGEBRAICA");
        SUMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUMAActionPerformed(evt);
            }
        });
        getContentPane().add(SUMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        PRODUCTO.setBackground(new java.awt.Color(102, 255, 204));
        PRODUCTO.setText("PRODUCTO");
        PRODUCTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRODUCTOActionPerformed(evt);
            }
        });
        getContentPane().add(PRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        COCIENTE.setBackground(new java.awt.Color(102, 255, 204));
        COCIENTE.setText("COCIENTE");
        COCIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COCIENTEActionPerformed(evt);
            }
        });
        getContentPane().add(COCIENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        TRIGONOMETRICA.setBackground(new java.awt.Color(102, 255, 204));
        TRIGONOMETRICA.setText("TRIGONOMETRICA");
        TRIGONOMETRICA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TRIGONOMETRICAActionPerformed(evt);
            }
        });
        getContentPane().add(TRIGONOMETRICA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("DERIVADAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 150, 38));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("DERIVADA DE LA FUNCIÓN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 170, 35));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("FUNCIÓN DERIVADA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 122, 35));

        DERIVADA.setBackground(new java.awt.Color(204, 204, 204));
        DERIVADA.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        DERIVADA.setEnabled(false);
        DERIVADA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DERIVADAActionPerformed(evt);
            }
        });
        getContentPane().add(DERIVADA, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 320, 35));

        X.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XActionPerformed(evt);
            }
        });
        getContentPane().add(X, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 220, 35));

        W.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        W.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WActionPerformed(evt);
            }
        });
        getContentPane().add(W, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 510, 220, 35));

        Wfuncion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Wfuncion.setText("FUNCIÓN W");
        getContentPane().add(Wfuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 520, 83, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("VALOR DE X");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("VALOR DE N");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, -1, -1));

        N.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NActionPerformed(evt);
            }
        });
        getContentPane().add(N, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 220, 35));

        Coseno.setBackground(new java.awt.Color(255, 102, 102));
        Coseno.setText("Coseno");
        Coseno.setEnabled(false);
        Coseno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CosenoActionPerformed(evt);
            }
        });
        getContentPane().add(Coseno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        Seno.setBackground(new java.awt.Color(255, 102, 102));
        Seno.setText("Seno");
        Seno.setEnabled(false);
        Seno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenoActionPerformed(evt);
            }
        });
        getContentPane().add(Seno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        Tangente.setBackground(new java.awt.Color(255, 102, 102));
        Tangente.setText("Tangente");
        Tangente.setEnabled(false);
        Tangente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TangenteActionPerformed(evt);
            }
        });
        getContentPane().add(Tangente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, -1, -1));

        Secante.setBackground(new java.awt.Color(255, 102, 102));
        Secante.setText("Secante");
        Secante.setEnabled(false);
        Secante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecanteActionPerformed(evt);
            }
        });
        getContentPane().add(Secante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        Cosecante.setBackground(new java.awt.Color(255, 102, 102));
        Cosecante.setText("Cosecante");
        Cosecante.setEnabled(false);
        Cosecante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CosecanteActionPerformed(evt);
            }
        });
        getContentPane().add(Cosecante, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, -1, -1));

        Cotangente.setBackground(new java.awt.Color(255, 102, 102));
        Cotangente.setText("Cotangente");
        Cotangente.setEnabled(false);
        Cotangente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CotangenteActionPerformed(evt);
            }
        });
        getContentPane().add(Cotangente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, -1, -1));

        BORRAR.setBackground(new java.awt.Color(255, 255, 153));
        BORRAR.setText("BORRAR");
        BORRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BORRARActionPerformed(evt);
            }
        });
        getContentPane().add(BORRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 110, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("VALOR DE K");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 83, -1));

        Ufuncion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Ufuncion.setText("FUNCIÓN U");
        getContentPane().add(Ufuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 83, 20));

        Vfuncion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Vfuncion.setText("FUNCIÓN V");
        getContentPane().add(Vfuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 83, 20));

        K1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        K1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                K1ActionPerformed(evt);
            }
        });
        getContentPane().add(K1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 220, 35));

        U.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        U.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UActionPerformed(evt);
            }
        });
        getContentPane().add(U, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, 220, 35));

        V.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VActionPerformed(evt);
            }
        });
        getContentPane().add(V, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, 220, 35));

        RESULTADO.setBackground(new java.awt.Color(204, 153, 255));
        RESULTADO.setText("RESULTADO");
        RESULTADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESULTADOActionPerformed(evt);
            }
        });
        getContentPane().add(RESULTADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 140, 50));

        UVWTrigonometrica.setText("TRIGONOMETRICA");
        UVWTrigonometrica.setEnabled(false);
        UVWTrigonometrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UVWTrigonometricaActionPerformed(evt);
            }
        });
        getContentPane().add(UVWTrigonometrica, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));

        UVWConstante.setText("CONSTANTE");
        UVWConstante.setEnabled(false);
        UVWConstante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UVWConstanteActionPerformed(evt);
            }
        });
        getContentPane().add(UVWConstante, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        UVWLineal.setText("LINEAL");
        UVWLineal.setEnabled(false);
        UVWLineal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UVWLinealActionPerformed(evt);
            }
        });
        getContentPane().add(UVWLineal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        UVWPotencial.setText("POTENCIAL");
        UVWPotencial.setEnabled(false);
        UVWPotencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UVWPotencialActionPerformed(evt);
            }
        });
        getContentPane().add(UVWPotencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("FUNCIONES");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));

        UVWCotangente.setText("Cotangente");
        UVWCotangente.setEnabled(false);
        UVWCotangente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UVWCotangenteActionPerformed(evt);
            }
        });
        getContentPane().add(UVWCotangente, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, -1, -1));

        UVWCoseno.setText("Coseno");
        UVWCoseno.setEnabled(false);
        UVWCoseno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UVWCosenoActionPerformed(evt);
            }
        });
        getContentPane().add(UVWCoseno, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, -1, -1));

        UVWSeno.setText("Seno");
        UVWSeno.setEnabled(false);
        UVWSeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UVWSenoActionPerformed(evt);
            }
        });
        getContentPane().add(UVWSeno, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));

        UVWTangente.setText("Tangente");
        UVWTangente.setEnabled(false);
        UVWTangente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UVWTangenteActionPerformed(evt);
            }
        });
        getContentPane().add(UVWTangente, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, -1, -1));

        UVWSecante.setText("Secante");
        UVWSecante.setEnabled(false);
        UVWSecante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UVWSecanteActionPerformed(evt);
            }
        });
        getContentPane().add(UVWSecante, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, -1, -1));

        UVWCosecante.setText("Cosecante");
        UVWCosecante.setEnabled(false);
        UVWCosecante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UVWCosecanteActionPerformed(evt);
            }
        });
        getContentPane().add(UVWCosecante, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, -1, -1));

        CasillaW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasillaWActionPerformed(evt);
            }
        });
        getContentPane().add(CasillaW, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, -1, -1));

        CasillaU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasillaUActionPerformed(evt);
            }
        });
        getContentPane().add(CasillaU, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, -1, -1));

        CasillaV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasillaVActionPerformed(evt);
            }
        });
        getContentPane().add(CasillaV, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void FUNCIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FUNCIONActionPerformed
        
    }//GEN-LAST:event_FUNCIONActionPerformed

    private void DERIVADAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DERIVADAActionPerformed
        
    }//GEN-LAST:event_DERIVADAActionPerformed

    private void XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XActionPerformed

    private void WActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WActionPerformed

    private void CONSTANTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONSTANTEActionPerformed
        FUNCION.setEnabled(true);
        DERIVADA.setEnabled(true);
        
        FUNCION.setText("Y=K");
        DERIVADA.setText("0");
        
        funcion = "constante";
        
        UVWConstante.setEnabled(false);
        UVWLineal.setEnabled(false);
        UVWPotencial.setEnabled(false);
        UVWTrigonometrica.setEnabled(false);
        UVWCoseno.setEnabled(false);
        UVWSeno.setEnabled(false);
        UVWTangente.setEnabled(false);
        UVWSecante.setEnabled(false);
        UVWCosecante.setEnabled(false);
        UVWCotangente.setEnabled(false);
        
        UVWConstante.setSelected(false);
        UVWLineal.setSelected(false);
        UVWPotencial.setSelected(false);
        UVWTrigonometrica.setSelected(false);
        UVWCoseno.setSelected(false);
        UVWSeno.setSelected(false);
        UVWTangente.setSelected(false);
        UVWSecante.setSelected(false);
        UVWCosecante.setSelected(false);
        UVWCotangente.setSelected(false);
    }//GEN-LAST:event_CONSTANTEActionPerformed

    private void LINEALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LINEALActionPerformed
        FUNCION.setEnabled(true);
        DERIVADA.setEnabled(true);

        FUNCION.setText("Y=X");
        DERIVADA.setText("1");
        
        funcion = "lineal";
        
        UVWConstante.setEnabled(false);
        UVWLineal.setEnabled(false);
        UVWPotencial.setEnabled(false);
        UVWTrigonometrica.setEnabled(false);
        UVWCoseno.setEnabled(false);
        UVWSeno.setEnabled(false);
        UVWTangente.setEnabled(false);
        UVWSecante.setEnabled(false);
        UVWCosecante.setEnabled(false);
        UVWCotangente.setEnabled(false);
        
        UVWConstante.setSelected(false);
        UVWLineal.setSelected(false);
        UVWPotencial.setSelected(false);
        UVWTrigonometrica.setSelected(false);
        UVWCoseno.setSelected(false);
        UVWSeno.setSelected(false);
        UVWTangente.setSelected(false);
        UVWSecante.setSelected(false);
        UVWCosecante.setSelected(false);
        UVWCotangente.setSelected(false);
    }//GEN-LAST:event_LINEALActionPerformed

    private void POTENCIALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_POTENCIALActionPerformed
        FUNCION.setEnabled(true);
        DERIVADA.setEnabled(true);
        
        FUNCION.setText("N(X^N-1)");
        DERIVADA.setText("");
        
        funcion = "potencial";

        UVWConstante.setEnabled(false);
        UVWLineal.setEnabled(false);
        UVWPotencial.setEnabled(false);
        UVWTrigonometrica.setEnabled(false);
        UVWCoseno.setEnabled(false);
        UVWSeno.setEnabled(false);
        UVWTangente.setEnabled(false);
        UVWSecante.setEnabled(false);
        UVWCosecante.setEnabled(false);
        UVWCotangente.setEnabled(false);
        
        UVWConstante.setSelected(false);
        UVWLineal.setSelected(false);
        UVWPotencial.setSelected(false);
        UVWTrigonometrica.setSelected(false);
        UVWCoseno.setSelected(false);
        UVWSeno.setSelected(false);
        UVWTangente.setSelected(false);
        UVWSecante.setSelected(false);
        UVWCosecante.setSelected(false);
        UVWCotangente.setSelected(false);
    }//GEN-LAST:event_POTENCIALActionPerformed

    private void NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NActionPerformed

    private void SUMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUMAActionPerformed
        FUNCION.setText("U'(x) + V'(x) + W'(x)");
        DERIVADA.setText("");
        
        FUNCION.setEnabled(true);
        DERIVADA.setEnabled(true);
        
        UVWConstante.setEnabled(true);
        UVWLineal.setEnabled(true);
        UVWPotencial.setEnabled(true);
        UVWTrigonometrica.setEnabled(true);
        
        funcion = "suma";
    }//GEN-LAST:event_SUMAActionPerformed

    private void PRODUCTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRODUCTOActionPerformed
        FUNCION.setText("(U'(x).V(x).W(x)) + (V'(x).U(x).W(x)) + (W'(x).U(x).V(x))");
        DERIVADA.setText("");
        
        FUNCION.setEnabled(true);
        DERIVADA.setEnabled(true);
        
        UVWConstante.setEnabled(true);
        UVWLineal.setEnabled(true);
        UVWPotencial.setEnabled(true);
        UVWTrigonometrica.setEnabled(true);
        
        funcion = "producto";        
    }//GEN-LAST:event_PRODUCTOActionPerformed

    private void COCIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COCIENTEActionPerformed
        FUNCION.setText("((U'(x).V(x)) - (V'(x).U(x))) / ((V(x))^2)");
        DERIVADA.setText("");
        
        FUNCION.setEnabled(true);
        DERIVADA.setEnabled(true);
        
        UVWConstante.setEnabled(true);
        UVWLineal.setEnabled(true);
        UVWPotencial.setEnabled(true);
        UVWTrigonometrica.setEnabled(true);
        
        funcion = "cociente";        
    }//GEN-LAST:event_COCIENTEActionPerformed

    private void TRIGONOMETRICAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TRIGONOMETRICAActionPerformed
        FUNCION.setText("");
        DERIVADA.setText("");
        
        Coseno.setEnabled(true);
        Seno.setEnabled(true);
        Tangente.setEnabled(true);
        Secante.setEnabled(true);
        Cosecante.setEnabled(true);
        Cotangente.setEnabled(true);
        
        funcion = "trigonometrica";
        
        UVWConstante.setEnabled(false);
        UVWLineal.setEnabled(false);
        UVWPotencial.setEnabled(false);
        UVWTrigonometrica.setEnabled(false);
        UVWCoseno.setEnabled(false);
        UVWSeno.setEnabled(false);
        UVWTangente.setEnabled(false);
        UVWSecante.setEnabled(false);
        UVWCosecante.setEnabled(false);
        UVWCotangente.setEnabled(false);
        
        UVWConstante.setSelected(false);
        UVWLineal.setSelected(false);
        UVWPotencial.setSelected(false);
        UVWTrigonometrica.setSelected(false);
        UVWCoseno.setSelected(false);
        UVWSeno.setSelected(false);
        UVWTangente.setSelected(false);
        UVWSecante.setSelected(false);
        UVWCosecante.setSelected(false);
        UVWCotangente.setSelected(false);
    }//GEN-LAST:event_TRIGONOMETRICAActionPerformed

    private void CosenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CosenoActionPerformed
        FUNCION.setEnabled(true);
        DERIVADA.setEnabled(true);
        
        FUNCION.setText("-SenX");
        DERIVADA.setText("");
        
        funcion = "coseno";
    }//GEN-LAST:event_CosenoActionPerformed

    private void SenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenoActionPerformed
        FUNCION.setEnabled(true);
        DERIVADA.setEnabled(true);
        
        FUNCION.setText("CosX");
        DERIVADA.setText("");
        
        funcion = "seno";
    }//GEN-LAST:event_SenoActionPerformed

    private void TangenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TangenteActionPerformed
        FUNCION.setEnabled(true);
        DERIVADA.setEnabled(true);

        FUNCION.setText("1/(Cos^2)*X");
        DERIVADA.setText("");
        
        funcion = "tangente";
    }//GEN-LAST:event_TangenteActionPerformed

    private void SecanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecanteActionPerformed
        FUNCION.setEnabled(true);
        DERIVADA.setEnabled(true);

        FUNCION.setText("SenX/(CosX)^2");
        DERIVADA.setText("");
        
        funcion = "secante";
    }//GEN-LAST:event_SecanteActionPerformed

    private void CosecanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CosecanteActionPerformed
        FUNCION.setEnabled(true);
        DERIVADA.setEnabled(true);

        FUNCION.setText("-(CosX/(SenX)^2)");
        DERIVADA.setText("");
        
        funcion = "cosecante";
    }//GEN-LAST:event_CosecanteActionPerformed

    private void CotangenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CotangenteActionPerformed
        FUNCION.setEnabled(true);
        DERIVADA.setEnabled(true);

        FUNCION.setText("-(1/(SenX)^2)");
        DERIVADA.setText("");
        
        funcion = "cotangente";
    }//GEN-LAST:event_CotangenteActionPerformed

    private void BORRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BORRARActionPerformed
        FUNCION.setText("");
        DERIVADA.setText("");
        X.setText("");
        N.setText("");
        W.setText("");
        
        FUNCION.setEnabled(false);
        DERIVADA.setEnabled(false);
        
        Coseno.setEnabled(false);
        Seno.setEnabled(false);
        Tangente.setEnabled(false);
        Secante.setEnabled(false);
        Cosecante.setEnabled(false);
        Cotangente.setEnabled(false);
        
        UVWConstante.setEnabled(false);
        UVWLineal.setEnabled(false);
        UVWPotencial.setEnabled(false);
        UVWTrigonometrica.setEnabled(false);
        UVWCoseno.setEnabled(false);
        UVWSeno.setEnabled(false);
        UVWTangente.setEnabled(false);
        UVWSecante.setEnabled(false);
        UVWCosecante.setEnabled(false);
        UVWCotangente.setEnabled(false);
        
        UVWConstante.setSelected(false);
        UVWLineal.setSelected(false);
        UVWPotencial.setSelected(false);
        UVWTrigonometrica.setSelected(false);
        UVWCoseno.setSelected(false);
        UVWSeno.setSelected(false);
        UVWTangente.setSelected(false);
        UVWSecante.setSelected(false);
        UVWCosecante.setSelected(false);
        UVWCotangente.setSelected(false);
    }//GEN-LAST:event_BORRARActionPerformed

    private void K1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_K1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_K1ActionPerformed

    private void UActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UActionPerformed

    private void VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VActionPerformed

    private void RESULTADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESULTADOActionPerformed
        if(funcion.equals("potencial"))
        {
            Nstring= N.getText();
            Nint = Integer.parseInt(Nstring);
        
            Xstring= X.getText();
            Xint= Integer.parseInt(Xstring);
        
            resta=Nint-1;
            ExponenteInt = (int)Math.pow(Xint, resta);
            ResultadoInt = Nint*ExponenteInt;
            ResultadoString= String.valueOf(ResultadoInt);
        
            DERIVADA.setText(ResultadoString);
        }
        
        if(funcion.equals("coseno"))
        {
            Xstring= X.getText();
            Xint= Integer.parseInt(Xstring);
        
            angulo = -(java.lang.Math.sin(Xint));
            ResultadoString = String.valueOf(angulo);
            DERIVADA.setText(ResultadoString);        
        }
        
        if(funcion.equals("seno"))
        {
            Xstring= X.getText();
            Xint= Integer.parseInt(Xstring);
        
            angulo = java.lang.Math.cos(Xint);
            ResultadoString = String.valueOf(angulo);
            DERIVADA.setText(ResultadoString);        
        }

        if(funcion.equals("tangente"))
        {
            Xstring= X.getText();
            Xint= Integer.parseInt(Xstring);
        
            angulo = java.lang.Math.cos(Xint);
            ExponenteDouble = (double)Math.pow(angulo, 2);
            ResultadoDouble = 1/ExponenteDouble;
            ResultadoString = String.valueOf(ResultadoDouble);
            DERIVADA.setText(ResultadoString);        
        } 
        
        if(funcion.equals("secante"))
        {
            Xstring= X.getText();
            Xint= Integer.parseInt(Xstring);
        
            angulo = java.lang.Math.sin(Xint);
            angulo2 = java.lang.Math.cos(Xint);
            ExponenteDouble = (double)Math.pow(angulo2, 2);
            ResultadoDouble = angulo/ExponenteDouble;
            ResultadoString = String.valueOf(ResultadoDouble);
            DERIVADA.setText(ResultadoString);        
        }

        if(funcion.equals("cosecante"))
        {
            Xstring= X.getText();
            Xint= Integer.parseInt(Xstring);
        
            angulo = java.lang.Math.cos(Xint);
            angulo2 = java.lang.Math.sin(Xint);
            ExponenteDouble = (double)Math.pow(angulo2, 2);
            ResultadoDouble = -(angulo/ExponenteDouble);
            ResultadoString = String.valueOf(ResultadoDouble);
            DERIVADA.setText(ResultadoString);        
        }

        if(funcion.equals("cotangente"))
        {
            Xstring= X.getText();
            Xint= Integer.parseInt(Xstring);
        
            angulo = java.lang.Math.sin(Xint);
            ExponenteDouble = (double)Math.pow(angulo, 2);
            ResultadoDouble = -(1/ExponenteDouble);
            ResultadoString = String.valueOf(ResultadoDouble);
            DERIVADA.setText(ResultadoString);        
        }

        if(funcion.equals("suma"))
        {
            
        }
        
        if(funcion.equals("producto"))
        {
            
        }
        
        if(funcion.equals("cociente"))
        {
            
        }
    }//GEN-LAST:event_RESULTADOActionPerformed

    private void UVWTrigonometricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UVWTrigonometricaActionPerformed
        UVWConstante.setSelected(false);
        UVWLineal.setSelected(false);
        UVWPotencial.setSelected(false);
        UVWCoseno.setSelected(false);
        UVWSeno.setSelected(false);
        UVWTangente.setSelected(false);
        UVWSecante.setSelected(false);
        UVWCosecante.setSelected(false);
        UVWCotangente.setSelected(false);
        
        UVWCoseno.setEnabled(true);
        UVWSeno.setEnabled(true);
        UVWTangente.setEnabled(true);
        UVWSecante.setEnabled(true);
        UVWCosecante.setEnabled(true);
        UVWCotangente.setEnabled(true);
    }//GEN-LAST:event_UVWTrigonometricaActionPerformed

    private void UVWConstanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UVWConstanteActionPerformed
        UVWLineal.setSelected(false);
        UVWPotencial.setSelected(false);
        UVWTrigonometrica.setSelected(false);
        UVWCoseno.setSelected(false);
        UVWSeno.setSelected(false);
        UVWTangente.setSelected(false);
        UVWSecante.setSelected(false);
        UVWCosecante.setSelected(false);
        UVWCotangente.setSelected(false);
    }//GEN-LAST:event_UVWConstanteActionPerformed

    private void UVWLinealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UVWLinealActionPerformed
        UVWConstante.setSelected(false);
        UVWPotencial.setSelected(false);
        UVWTrigonometrica.setSelected(false);
        UVWCoseno.setSelected(false);
        UVWSeno.setSelected(false);
        UVWTangente.setSelected(false);
        UVWSecante.setSelected(false);
        UVWCosecante.setSelected(false);
        UVWCotangente.setSelected(false);
    }//GEN-LAST:event_UVWLinealActionPerformed

    private void UVWPotencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UVWPotencialActionPerformed
        UVWConstante.setSelected(false);
        UVWLineal.setSelected(false);
        UVWTrigonometrica.setSelected(false);
        UVWCoseno.setSelected(false);
        UVWSeno.setSelected(false);
        UVWTangente.setSelected(false);
        UVWSecante.setSelected(false);
        UVWCosecante.setSelected(false);
        UVWCotangente.setSelected(false);
    }//GEN-LAST:event_UVWPotencialActionPerformed

    private void CasillaUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasillaUActionPerformed
        CasillaV.setSelected(false);
        CasillaW.setSelected(false);
        
        if(UVWConstante.isSelected()==true)
        {
            U.setText("Y=K");
        }
        
        if(UVWLineal.isSelected()==true)
        {
            U.setText("Y=X");
        }
        
        if(UVWPotencial.isSelected()==true)
        {
            U.setText("N(X^N-1)");
        }

        if(UVWCoseno.isSelected()==true)
        {
            U.setText("-SenX");
        }

        if(UVWSeno.isSelected()==true)
        {
            U.setText("CosX");
        }

        if(UVWTangente.isSelected()==true)
        {
            U.setText("1/(Cos^2)*X");
        }

        if(UVWSecante.isSelected()==true)
        {
            U.setText("SenX/(CosX)^2");
        }

        if(UVWCosecante.isSelected()==true)
        {
            U.setText("-(CosX/(SenX)^2)");
        }

        if(UVWCotangente.isSelected()==true)
        {
            U.setText("-(1/(SenX)^2)");
        }        
    }//GEN-LAST:event_CasillaUActionPerformed

    private void CasillaVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasillaVActionPerformed
        CasillaU.setSelected(false);
        CasillaW.setSelected(false);
        
        if(UVWConstante.isSelected()==true)
        {
            V.setText("Y=K");
        }
        
        if(UVWLineal.isSelected()==true)
        {
            V.setText("Y=X");
        }
        
        if(UVWPotencial.isSelected()==true)
        {
            V.setText("N(X^N-1)");
        }

        if(UVWCoseno.isSelected()==true)
        {
            V.setText("-SenX");
        }

        if(UVWSeno.isSelected()==true)
        {
            V.setText("CosX");
        }

        if(UVWTangente.isSelected()==true)
        {
            V.setText("1/(Cos^2)*X");
        }

        if(UVWSecante.isSelected()==true)
        {
            V.setText("SenX/(CosX)^2");
        }

        if(UVWCosecante.isSelected()==true)
        {
            V.setText("-(CosX/(SenX)^2)");
        }

        if(UVWCotangente.isSelected()==true)
        {
            V.setText("-(1/(SenX)^2)");
        }        
    }//GEN-LAST:event_CasillaVActionPerformed

    private void CasillaWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasillaWActionPerformed
        CasillaU.setSelected(false);
        CasillaV.setSelected(false);

        if(UVWConstante.isSelected()==true)
        {
            W.setText("Y=K");
        }
        
        if(UVWLineal.isSelected()==true)
        {
            W.setText("Y=X");
        }
        
        if(UVWPotencial.isSelected()==true)
        {
            W.setText("N(X^N-1)");
        }

        if(UVWCoseno.isSelected()==true)
        {
            W.setText("-SenX");
        }

        if(UVWSeno.isSelected()==true)
        {
            W.setText("CosX");
        }

        if(UVWTangente.isSelected()==true)
        {
            W.setText("1/(Cos^2)*X");
        }

        if(UVWSecante.isSelected()==true)
        {
            W.setText("SenX/(CosX)^2");
        }

        if(UVWCosecante.isSelected()==true)
        {
            W.setText("-(CosX/(SenX)^2)");
        }

        if(UVWCotangente.isSelected()==true)
        {
            W.setText("-(1/(SenX)^2)");
        } 
    }//GEN-LAST:event_CasillaWActionPerformed

    private void UVWCosenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UVWCosenoActionPerformed
        UVWConstante.setSelected(false);
        UVWLineal.setSelected(false);
        UVWPotencial.setSelected(false);
        UVWTrigonometrica.setSelected(false);
        UVWSeno.setSelected(false);
        UVWTangente.setSelected(false);
        UVWSecante.setSelected(false);
        UVWCosecante.setSelected(false);
        UVWCotangente.setSelected(false);
    }//GEN-LAST:event_UVWCosenoActionPerformed

    private void UVWSenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UVWSenoActionPerformed
        UVWConstante.setSelected(false);
        UVWLineal.setSelected(false);
        UVWPotencial.setSelected(false);
        UVWTrigonometrica.setSelected(false);
        UVWCoseno.setSelected(false);
        UVWTangente.setSelected(false);
        UVWSecante.setSelected(false);
        UVWCosecante.setSelected(false);
        UVWCotangente.setSelected(false);
    }//GEN-LAST:event_UVWSenoActionPerformed

    private void UVWTangenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UVWTangenteActionPerformed
        UVWConstante.setSelected(false);
        UVWLineal.setSelected(false);
        UVWPotencial.setSelected(false);
        UVWTrigonometrica.setSelected(false);
        UVWCoseno.setSelected(false);
        UVWSeno.setSelected(false);
        UVWSecante.setSelected(false);
        UVWCosecante.setSelected(false);
        UVWCotangente.setSelected(false);
    }//GEN-LAST:event_UVWTangenteActionPerformed

    private void UVWSecanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UVWSecanteActionPerformed
        UVWConstante.setSelected(false);
        UVWLineal.setSelected(false);
        UVWPotencial.setSelected(false);
        UVWTrigonometrica.setSelected(false);
        UVWCoseno.setSelected(false);
        UVWSeno.setSelected(false);
        UVWTangente.setSelected(false);
        UVWCosecante.setSelected(false);
        UVWCotangente.setSelected(false);
    }//GEN-LAST:event_UVWSecanteActionPerformed

    private void UVWCosecanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UVWCosecanteActionPerformed
        UVWConstante.setSelected(false);
        UVWLineal.setSelected(false);
        UVWPotencial.setSelected(false);
        UVWTrigonometrica.setSelected(false);
        UVWCoseno.setSelected(false);
        UVWSeno.setSelected(false);
        UVWTangente.setSelected(false);
        UVWSecante.setSelected(false);
        UVWCotangente.setSelected(false);
    }//GEN-LAST:event_UVWCosecanteActionPerformed

    private void UVWCotangenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UVWCotangenteActionPerformed
        UVWConstante.setSelected(false);
        UVWLineal.setSelected(false);
        UVWPotencial.setSelected(false);
        UVWTrigonometrica.setSelected(false);
        UVWCoseno.setSelected(false);
        UVWSeno.setSelected(false);
        UVWTangente.setSelected(false);
        UVWSecante.setSelected(false);
        UVWCosecante.setSelected(false);
    }//GEN-LAST:event_UVWCotangenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BORRAR;
    private javax.swing.JButton COCIENTE;
    private javax.swing.JButton CONSTANTE;
    private javax.swing.JCheckBox CasillaU;
    private javax.swing.JCheckBox CasillaV;
    private javax.swing.JCheckBox CasillaW;
    private javax.swing.JButton Cosecante;
    private javax.swing.JButton Coseno;
    private javax.swing.JButton Cotangente;
    private javax.swing.JTextField DERIVADA;
    private javax.swing.JTextField FUNCION;
    private javax.swing.JTextField K1;
    private javax.swing.JButton LINEAL;
    private javax.swing.JTextField N;
    private javax.swing.JButton POTENCIAL;
    private javax.swing.JButton PRODUCTO;
    private javax.swing.JButton RESULTADO;
    private javax.swing.JButton SUMA;
    private javax.swing.JButton Secante;
    private javax.swing.JButton Seno;
    private javax.swing.JButton TRIGONOMETRICA;
    private javax.swing.JButton Tangente;
    private javax.swing.JTextField U;
    private javax.swing.JRadioButton UVWConstante;
    private javax.swing.JRadioButton UVWCosecante;
    private javax.swing.JRadioButton UVWCoseno;
    private javax.swing.JRadioButton UVWCotangente;
    private javax.swing.JRadioButton UVWLineal;
    private javax.swing.JRadioButton UVWPotencial;
    private javax.swing.JRadioButton UVWSecante;
    private javax.swing.JRadioButton UVWSeno;
    private javax.swing.JRadioButton UVWTangente;
    private javax.swing.JRadioButton UVWTrigonometrica;
    private javax.swing.JLabel Ufuncion;
    private javax.swing.JTextField V;
    private javax.swing.JLabel Vfuncion;
    private javax.swing.JTextField W;
    private javax.swing.JLabel Wfuncion;
    private javax.swing.JTextField X;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
